language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-web *
  - mkdir -p deploy
  - mv spring-web.zip deploy/spring-web.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-aws-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-aws-build
    key: spring-web.zip
    bundle_type: zip
    application: spring-web
    deployment_group: spring-web-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yeojin7010@gmail.com
